//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAuthorizableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAuthorizableObject()
        {
            this.MAspnetRolesGAuthorizableObjects = new HashSet<MAspnetRolesGAuthorizableObject>();
        }
    
        public int Id { get; set; }
        public string GaoControllerName { get; set; }
        public string GaoControllerMethodName { get; set; }
        public string GaoDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAspnetRolesGAuthorizableObject> MAspnetRolesGAuthorizableObjects { get; set; }
    }
}
