//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEmailConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEmailConfiguration()
        {
            this.LEmailBuckets = new HashSet<LEmailBucket>();
        }
    
        public int Id { get; set; }
        public string GecAccountName { get; set; }
        public string GecAccountDescription { get; set; }
        public string GecEmailId { get; set; }
        public string GecDisplayName { get; set; }
        public string GecReplyTo { get; set; }
        public string GelSmtpHost { get; set; }
        public int GecPortNumber { get; set; }
        public string GecSmtpLoginId { get; set; }
        public string GecSMTPPassword { get; set; }
        public bool GecRequiresSSL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEmailBucket> LEmailBuckets { get; set; }
    }
}
