//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GErrorLog
    {
        public int Id { get; set; }
        public System.DateTime GelErrorDateTime { get; set; }
        public string GelSourceProject { get; set; }
        public string GelController { get; set; }
        public string GelMethod { get; set; }
        public string GelStackTrace { get; set; }
        public string GelUserName { get; set; }
        public string GelErrorType { get; set; }
        public string GelErrorDescription { get; set; }
        public string GelResolution { get; set; }
        public string GelErrorOwner { get; set; }
        public string GelFieldName { get; set; }
        public Nullable<int> GelSOSBatchNumber { get; set; }
        public string GelStatus { get; set; }
    }
}
