//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GMenu()
        {
            this.MGMenusAspnetRoles = new HashSet<MGMenusAspnetRole>();
            this.GMenus1 = new HashSet<GMenu>();
        }
    
        public int Id { get; set; }
        public Nullable<int> GmParentId { get; set; }
        public string GmMenuName { get; set; }
        public string GmMenuUrl { get; set; }
        public int GmOrdinalPosition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MGMenusAspnetRole> MGMenusAspnetRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GMenu> GMenus1 { get; set; }
        public virtual GMenu GMenu1 { get; set; }
    }
}
