//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAudit
    {
        public int Id { get; set; }
        public string LaSOSProcessName { get; set; }
        public string LaL3ProcessName { get; set; }
        public string LaControlCode { get; set; }
        public string LaControlDescription { get; set; }
        public string LaAction { get; set; }
        public string LaActionType { get; set; }
        public string LaActionedById { get; set; }
        public System.DateTime LaActioDateTime { get; set; }
        public string LaOldStatus { get; set; }
        public string LaNewStatus { get; set; }
        public string LaEntityType { get; set; }
        public int LaEntityId { get; set; }
        public string LaEntityName { get; set; }
        public Nullable<int> LaWorkflowId { get; set; }
        public int LaCompanyId { get; set; }
        public string LaRoleId { get; set; }
        public string LaPeriod { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual GCompany GCompany { get; set; }
        public virtual RWorkFlow RWorkFlow { get; set; }
    }
}
