//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LBatch()
        {
            this.LBatches1 = new HashSet<LBatch>();
            this.LBatchFiles = new HashSet<LBatchFile>();
        }
    
        public int Id { get; set; }
        public int LbCompanyId { get; set; }
        public string LbUpdatedBy { get; set; }
        public Nullable<int> LbParentBatchId { get; set; }
        public Nullable<int> LbRawDataTableId { get; set; }
        public int LbBatchNumber { get; set; }
        public System.DateTime LbUploadStartDateTime { get; set; }
        public Nullable<System.DateTime> LbUploadFinishDateTime { get; set; }
        public string LbBatchType { get; set; }
        public Nullable<int> LbRecordCount { get; set; }
        public Nullable<int> LbAlteryxBatchNumber { get; set; }
        public string LbComments { get; set; }
        public string LbCommissionPeriod { get; set; }
        public string LballocatedToId { get; set; }
        public string LbStatus { get; set; }
        public string WFRequesterId { get; set; }
        public string WFAnalystId { get; set; }
        public string WFManagerId { get; set; }
        public Nullable<int> WFOrdinal { get; set; }
        public string WFCurrentOwnerId { get; set; }
        public string WFStatus { get; set; }
        public string WFType { get; set; }
        public string WFRequesterRoleId { get; set; }
        public int WFCompanyId { get; set; }
        public string WFComments { get; set; }
        public string LbBatchName { get; set; }
        public string A01 { get; set; }
        public string A02 { get; set; }
        public string A03 { get; set; }
        public string A04 { get; set; }
        public string A05 { get; set; }
        public Nullable<int> LbPeriodCode { get; set; }
        public string ParameterCarrier { get; set; }
        public Nullable<int> LbBatchValue { get; set; }
        public Nullable<System.DateTime> WFUpdatedDateTime { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual GCompany GCompany { get; set; }
        public virtual GCompany GCompany1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LBatch> LBatches1 { get; set; }
        public virtual LBatch LBatch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LBatchFile> LBatchFiles { get; set; }
        public virtual LRawDataTable LRawDataTable { get; set; }
    }
}
