//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LClaim
    {
        public int Id { get; set; }
        public int LcCompanyId { get; set; }
        public string LcCreatedById { get; set; }
        public Nullable<int> LcBrandId { get; set; }
        public Nullable<int> LcActivityTypeId { get; set; }
        public Nullable<int> LcCommissionTypeId { get; set; }
        public string LcAllocatedToId { get; set; }
        public string LcAllocatedById { get; set; }
        public Nullable<int> LcRejectionReasonId { get; set; }
        public Nullable<int> LcPaymentCommissionTypeId { get; set; }
        public string LcApprovedById { get; set; }
        public string LcSentForApprovalById { get; set; }
        public string LcWithdrawnById { get; set; }
        public string LcRejectedById { get; set; }
        public Nullable<int> LcDeviceTypeId { get; set; }
        public long LcClaimId { get; set; }
        public Nullable<System.DateTime> LcConnectionDate { get; set; }
        public Nullable<System.DateTime> LcOrderDate { get; set; }
        public Nullable<int> LcProductCodeId { get; set; }
        public decimal LcExpectedCommissionAmount { get; set; }
        public bool LcIsDuplicateClaim { get; set; }
        public string LcDuplicateClaimDetails { get; set; }
        public Nullable<System.DateTime> LcAllocationDate { get; set; }
        public bool LcIsReclaim { get; set; }
        public Nullable<decimal> LcAlreadyPaidAmount { get; set; }
        public Nullable<System.DateTime> LcAlreadyPaidDate { get; set; }
        public string LcAlreadyPaidDealer { get; set; }
        public string LcReasonNonAutoPayment { get; set; }
        public string LcClawbackPayeeCode { get; set; }
        public Nullable<decimal> LcClawbackAmount { get; set; }
        public Nullable<System.DateTime> LcSentForApprovalDate { get; set; }
        public Nullable<System.DateTime> LcApprovalDate { get; set; }
        public Nullable<System.DateTime> LcPaymentDate { get; set; }
        public Nullable<System.DateTime> LcLastReclaimDate { get; set; }
        public Nullable<System.DateTime> LcWithdrawnDate { get; set; }
        public Nullable<System.DateTime> LcRejectionDate { get; set; }
        public Nullable<decimal> LcPaymentAmount { get; set; }
        public Nullable<int> LcPaymentBatchNumber { get; set; }
        public Nullable<int> LcClaimBatchNumber { get; set; }
        public Nullable<System.DateTime> LcCreatedDateTime { get; set; }
        public string WFRequesterId { get; set; }
        public string WFAnalystId { get; set; }
        public string WFManagerId { get; set; }
        public Nullable<int> WFOrdinal { get; set; }
        public string WFCurrentOwnerId { get; set; }
        public string WFStatus { get; set; }
        public string WFType { get; set; }
        public string WFRequesterRoleId { get; set; }
        public int WFCompanyId { get; set; }
        public string WFComments { get; set; }
        public int LcPayeeId { get; set; }
        public string ParameterCarrier { get; set; }
        public bool LcCreatedByForm { get; set; }
        public byte[] LcMSISDN { get; set; }
        public byte[] LcCustomerName { get; set; }
        public byte[] LcBAN { get; set; }
        public byte[] LcIMEI { get; set; }
        public byte[] LcOrderNumber { get; set; }
        public byte[] A01 { get; set; }
        public byte[] A02 { get; set; }
        public byte[] A03 { get; set; }
        public byte[] A04 { get; set; }
        public byte[] A05 { get; set; }
        public byte[] A06 { get; set; }
        public byte[] A07 { get; set; }
        public byte[] A08 { get; set; }
        public byte[] A09 { get; set; }
        public byte[] A10 { get; set; }
        public string LcCommissionPeriod { get; set; }
        public Nullable<int> LcParentPayeeId { get; set; }
        public Nullable<System.DateTime> WFUpdatedDateTime { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual AspNetUser AspNetUser6 { get; set; }
        public virtual AspNetUser AspNetUser7 { get; set; }
        public virtual AspNetUser AspNetUser8 { get; set; }
        public virtual AspNetUser AspNetUser9 { get; set; }
        public virtual AspNetUser AspNetUser10 { get; set; }
        public virtual GCompany GCompany { get; set; }
        public virtual GCompany GCompany1 { get; set; }
        public virtual LPayee LPayee { get; set; }
        public virtual RActivityType RActivityType { get; set; }
        public virtual RBrand RBrand { get; set; }
        public virtual RCommissionType RCommissionType { get; set; }
        public virtual RCommissionType RCommissionType1 { get; set; }
        public virtual RCommissionType RCommissionType2 { get; set; }
        public virtual RDeviceType RDeviceType { get; set; }
        public virtual RProductCode RProductCode { get; set; }
        public virtual RRejectionReason RRejectionReason { get; set; }
    }
}
