//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCompanySpecificColumn
    {
        public int Id { get; set; }
        public int LcscCompanyId { get; set; }
        public string LcscTableName { get; set; }
        public string LcscColumnName { get; set; }
        public string LcscLabel { get; set; }
        public bool LcscDisplayOnForm { get; set; }
        public int LcscOrdinalPosition { get; set; }
        public Nullable<bool> LcscIsMandatory { get; set; }
        public Nullable<int> LcscDropDownId { get; set; }
        public Nullable<bool> LcscIsReportParameter { get; set; }
        public Nullable<int> LcscReportParameterOrdinal { get; set; }
        public string LcscDataType { get; set; }
        public string LcscTooltip { get; set; }
    
        public virtual GCompany GCompany { get; set; }
        public virtual LDropDown LDropDown { get; set; }
    }
}
