//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCompanySpecificRawDataColumn
    {
        public int Id { get; set; }
        public int LcsrdcRawDataTableId { get; set; }
        public string LcsrdcDisplayLabel { get; set; }
        public string LcsrdcDataType { get; set; }
        public int LcsrdcOrdinalPosition { get; set; }
        public Nullable<bool> LcsrdcIsDisplayable { get; set; }
        public string LcsrdcXColumnName { get; set; }
    
        public virtual LRawDataTable LRawDataTable { get; set; }
    }
}
