//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCommissionPeriod
    {
        public int Id { get; set; }
        public int LcpCompanyId { get; set; }
        public string LcpCreatedById { get; set; }
        public string LcpUpdatedById { get; set; }
        public string LcpPeriodName { get; set; }
        public System.DateTime LcpCreatedDateTime { get; set; }
        public System.DateTime LcpUpdatedDateTime { get; set; }
        public string LcpStatus { get; set; }
        public Nullable<int> LcpPeriodCode { get; set; }
        public string LcpPeriodType { get; set; }
        public Nullable<int> LcpDatabaseId { get; set; }
        public Nullable<System.DateTime> LcpEffectiveStartDate { get; set; }
        public Nullable<System.DateTime> LcpEffectiveEndDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual GCompany GCompany { get; set; }
        public virtual LDatabas LDatabas { get; set; }
    }
}
