//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCommissionBatchAllocationRule
    {
        public int Id { get; set; }
        public string LrdbarPrimaryChannel { get; set; }
        public string LrdbarBusinessUnit { get; set; }
        public string LrdbarChannel { get; set; }
        public string LrdbarAllocateToId { get; set; }
        public int LrdbarCompanyId { get; set; }
        public bool LrdbarIsDefault { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual GCompany GCompany { get; set; }
    }
}
