//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDashboardConfig
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string RoleId { get; set; }
        public int KpiTypeId { get; set; }
        public int KpiGroupId { get; set; }
        public string KpiIds { get; set; }
        public string PeriodIntervals { get; set; }
        public string PortfolioIds { get; set; }
        public string PayeeCodes { get; set; }
        public string Dimension { get; set; }
        public string GraphType { get; set; }
        public Nullable<int> TileOrdinal { get; set; }
        public string TileLabel { get; set; }
        public int CompanyId { get; set; }
        public bool IsGraph { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual GCompany GCompany { get; set; }
    }
}
