//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDatabas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LDatabas()
        {
            this.LCommissionPeriods = new HashSet<LCommissionPeriod>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string HostName { get; set; }
        public string DatabaseName { get; set; }
        public string LoginId { get; set; }
        public string SchemaName { get; set; }
        public string LinkServerName { get; set; }
        public byte[] Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LCommissionPeriod> LCommissionPeriods { get; set; }
    }
}
