//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEmailBucket
    {
        public int Id { get; set; }
        public string LebRecipientList { get; set; }
        public string LebCCList { get; set; }
        public string LebBCCList { get; set; }
        public string LebReplyToList { get; set; }
        public string LebSubject { get; set; }
        public string LebBody { get; set; }
        public bool LebIsHTML { get; set; }
        public string LebEmailType { get; set; }
        public string LebPriority { get; set; }
        public string LebAttachmentList { get; set; }
        public string LebStatus { get; set; }
        public string LebComments { get; set; }
        public System.DateTime LebCreatedDateTime { get; set; }
        public System.DateTime LebUpdatedDateTime { get; set; }
        public string LebCreatedById { get; set; }
        public string LebUpdatedById { get; set; }
        public int LebSenderConfigId { get; set; }
        public string LebBucketName { get; set; }
        public string LebAccessKey { get; set; }
        public string LebSecretKey { get; set; }
        public Nullable<System.DateTime> LebSendDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual GEmailConfiguration GEmailConfiguration { get; set; }
    }
}
