//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMessageRecipient
    {
        public int Id { get; set; }
        public int MessageID { get; set; }
        public string RecipientID { get; set; }
        public int RecipientRoleID { get; set; }
        public Nullable<System.DateTime> ReadRecieptDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LMessage LMessage { get; set; }
    }
}
