//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LNotification
    {
        public int id { get; set; }
        public int CompanyId { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> RemindAfterDays { get; set; }
        public Nullable<int> ReminderIntervalDays { get; set; }
        public Nullable<int> StopAfterDays { get; set; }
        public int EmailTemplateId { get; set; }
        public int LandingConfigId { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public string RecipientRoleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Recipient { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual GCompany GCompany { get; set; }
        public virtual LEmailTemplate LEmailTemplate { get; set; }
        public virtual LWorkFlowConfig LWorkFlowConfig { get; set; }
    }
}
