//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPasswordPolicy
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int MinLength { get; set; }
        public int MinUppercase { get; set; }
        public int MinLowercase { get; set; }
        public int MinNumbers { get; set; }
        public int MinSpecialChars { get; set; }
        public int MaxAgeDays { get; set; }
        public int ReminderDays { get; set; }
        public int MinAgeDays { get; set; }
        public int PreventReuse { get; set; }
        public int LockoutFailedAttempts { get; set; }
        public int LockoutMins { get; set; }
        public Nullable<int> MFAOTPValidMins { get; set; }
    }
}
