//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPayee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LPayee()
        {
            this.LClaims = new HashSet<LClaim>();
            this.LPayeeParents = new HashSet<LPayeeParent>();
            this.LPayeeParents1 = new HashSet<LPayeeParent>();
            this.MDocumentSetsPayees = new HashSet<MDocumentSetsPayee>();
        }
    
        public int Id { get; set; }
        public string LpUserId { get; set; }
        public int LpCompanyId { get; set; }
        public Nullable<int> LpChannelId { get; set; }
        public Nullable<int> LpSubChannelId { get; set; }
        public string LpCreatedById { get; set; }
        public string LpUpdatedById { get; set; }
        public string LpPrimaryChannel { get; set; }
        public string LpPayeeCode { get; set; }
        public string LpEmail { get; set; }
        public System.DateTime LpEffectiveStartDate { get; set; }
        public Nullable<System.DateTime> LpEffectiveEndDate { get; set; }
        public string LpFileNames { get; set; }
        public string LpUserFriendlyFileNames { get; set; }
        public string LpBusinessUnit { get; set; }
        public bool LpCanRaiseClaims { get; set; }
        public string LpChannelManager { get; set; }
        public Nullable<System.DateTime> LpCreatedDateTime { get; set; }
        public Nullable<System.DateTime> LpUpdatedDateTime { get; set; }
        public string LpTIN { get; set; }
        public string LpDistributionChannel { get; set; }
        public string LpPosition { get; set; }
        public Nullable<int> LpBatchNumber { get; set; }
        public bool LpCreateLogin { get; set; }
        public string WFRequesterId { get; set; }
        public string WFAnalystId { get; set; }
        public string WFManagerId { get; set; }
        public Nullable<int> WFOrdinal { get; set; }
        public string WFCurrentOwnerId { get; set; }
        public string WFStatus { get; set; }
        public string WFType { get; set; }
        public string WFRequesterRoleId { get; set; }
        public int WFCompanyId { get; set; }
        public string WFComments { get; set; }
        public string LpFinOpsRoles { get; set; }
        public string ParameterCarrier { get; set; }
        public bool LpCreatedByForm { get; set; }
        public byte[] LpPhone { get; set; }
        public byte[] LpAddress { get; set; }
        public byte[] A01 { get; set; }
        public byte[] A02 { get; set; }
        public byte[] A03 { get; set; }
        public byte[] A04 { get; set; }
        public byte[] A05 { get; set; }
        public byte[] A06 { get; set; }
        public byte[] A07 { get; set; }
        public byte[] A08 { get; set; }
        public byte[] A09 { get; set; }
        public byte[] A10 { get; set; }
        public bool LpBlockNotification { get; set; }
        public byte[] LpFirstName { get; set; }
        public byte[] LpLastName { get; set; }
        public byte[] LpTradingName { get; set; }
        public Nullable<System.DateTime> WFUpdatedDateTime { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual AspNetUser AspNetUser6 { get; set; }
        public virtual GCompany GCompany { get; set; }
        public virtual GCompany GCompany1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LClaim> LClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LPayeeParent> LPayeeParents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LPayeeParent> LPayeeParents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDocumentSetsPayee> MDocumentSetsPayees { get; set; }
        public virtual RChannel RChannel { get; set; }
        public virtual RSubChannel RSubChannel { get; set; }
    }
}
