//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPortfolio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LPortfolio()
        {
            this.LReadyToPayPortfolios = new HashSet<LReadyToPayPortfolio>();
            this.MEntityPortfolios = new HashSet<MEntityPortfolio>();
            this.MSupportTicketPortfolios = new HashSet<MSupportTicketPortfolio>();
        }
    
        public int Id { get; set; }
        public int LpCompanyId { get; set; }
        public string LpBusinessUnit { get; set; }
        public int LpChannelId { get; set; }
        public Nullable<bool> LpIsActive { get; set; }
    
        public virtual GCompany GCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReadyToPayPortfolio> LReadyToPayPortfolios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEntityPortfolio> MEntityPortfolios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSupportTicketPortfolio> MSupportTicketPortfolios { get; set; }
        public virtual RChannel RChannel { get; set; }
    }
}
