//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LRefFileType
    {
        public int Id { get; set; }
        public int LrftCompanyId { get; set; }
        public string LrftCreatedById { get; set; }
        public string LrftUpdatedById { get; set; }
        public string LrftName { get; set; }
        public string LrftDescription { get; set; }
        public Nullable<System.DateTime> LrftCreatedDateTime { get; set; }
        public Nullable<System.DateTime> LrftUpdatedDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual GCompany GCompany { get; set; }
    }
}
