//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSupportTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LSupportTicket()
        {
            this.LSupportResponses = new HashSet<LSupportRespons>();
            this.LSupportTicketAssignments = new HashSet<LSupportTicketAssignment>();
        }
    
        public int Id { get; set; }
        public string LstTicketNumber { get; set; }
        public string LstPhone { get; set; }
        public string LstType { get; set; }
        public string LstClosureCode { get; set; }
        public string LstSeverity { get; set; }
        public string LstImpact { get; set; }
        public string LstPriority { get; set; }
        public string LstSummary { get; set; }
        public System.DateTime LstCreatedDateTime { get; set; }
        public string LstCC { get; set; }
        public string LstStatus { get; set; }
        public System.DateTime LstLastUpdatedDateTime { get; set; }
        public Nullable<int> LstTeamId { get; set; }
        public string LstCreatedById { get; set; }
        public int LstCompanyId { get; set; }
        public string LstCreatedOnBehalfOfId { get; set; }
        public string LstLastUpdatedById { get; set; }
        public string LstL1Id { get; set; }
        public string LstL2Id { get; set; }
        public string LstL3Id { get; set; }
        public string LstCurrentOwnerId { get; set; }
        public int LstCategoryId { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public Nullable<int> LstStageId { get; set; }
        public Nullable<int> LstForCompanyId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual AspNetUser AspNetUser6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LSupportRespons> LSupportResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LSupportTicketAssignment> LSupportTicketAssignments { get; set; }
        public virtual RSupportCategory RSupportCategory { get; set; }
        public virtual RsupportTeam RsupportTeam { get; set; }
        public virtual RTicketStage RTicketStage { get; set; }
    }
}
