//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSupportRespons
    {
        public int Id { get; set; }
        public System.DateTime LsrResponseDateTime { get; set; }
        public string LsrDescription { get; set; }
        public string LsrUploadedFileNames { get; set; }
        public string LsrTicketStatus { get; set; }
        public int LsrSupportTicketId { get; set; }
        public string LsrResponseById { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LSupportTicket LSupportTicket { get; set; }
    }
}
