//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSupportTicketAssignment
    {
        public int Id { get; set; }
        public System.DateTime LstaCreatedDateTime { get; set; }
        public int LstaSupportTicketId { get; set; }
        public string LstaAssignedToId { get; set; }
        public string LstaAssignedById { get; set; }
        public int LstaSupportTeamId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual LSupportTicket LSupportTicket { get; set; }
        public virtual RsupportTeam RsupportTeam { get; set; }
    }
}
