//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUser
    {
        public int Id { get; set; }
        public string LuUserId { get; set; }
        public int LuCompanyId { get; set; }
        public string LuCreatedById { get; set; }
        public string LuUpdatedById { get; set; }
        public string LuFirstName { get; set; }
        public string LuLastName { get; set; }
        public string LuEmail { get; set; }
        public string LuPhone { get; set; }
        public bool LuIsManager { get; set; }
        public string LuBand { get; set; }
        public string LuStatus { get; set; }
        public System.DateTime LuCreatedDateTime { get; set; }
        public System.DateTime LuUpdatedDateTime { get; set; }
        public string A01 { get; set; }
        public string A02 { get; set; }
        public string A03 { get; set; }
        public string A04 { get; set; }
        public string A05 { get; set; }
        public Nullable<decimal> AN01 { get; set; }
        public Nullable<decimal> AN02 { get; set; }
        public Nullable<decimal> AN03 { get; set; }
        public Nullable<decimal> AN04 { get; set; }
        public Nullable<decimal> AN05 { get; set; }
        public Nullable<System.DateTime> AD01 { get; set; }
        public Nullable<System.DateTime> AD02 { get; set; }
        public Nullable<System.DateTime> AD03 { get; set; }
        public Nullable<System.DateTime> AD04 { get; set; }
        public Nullable<System.DateTime> AD05 { get; set; }
        public string LuReportsToId { get; set; }
        public bool LuIsAlteryxUser { get; set; }
        public bool LuBlockNotification { get; set; }
        public string WFRequesterId { get; set; }
        public string WFAnalystId { get; set; }
        public string WFManagerId { get; set; }
        public Nullable<int> WFOrdinal { get; set; }
        public string WFCurrentOwnerId { get; set; }
        public string WFStatus { get; set; }
        public string WFType { get; set; }
        public string WFRequesterRoleId { get; set; }
        public int WFCompanyId { get; set; }
        public string WFComments { get; set; }
        public string ParameterCarrier { get; set; }
        public Nullable<bool> LuCreateLogin { get; set; }
        public Nullable<bool> LuCreatedByForm { get; set; }
        public Nullable<System.DateTime> WFUpdatedDateTime { get; set; }
        public Nullable<bool> IsSuperUser { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual AspNetUser AspNetUser6 { get; set; }
        public virtual AspNetUser AspNetUser7 { get; set; }
        public virtual GCompany GCompany { get; set; }
        public virtual GCompany GCompany1 { get; set; }
    }
}
