//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUserLobby
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string UserType { get; set; }
        public string PayeeCode { get; set; }
        public bool IsVFADUser { get; set; }
        public string Status { get; set; }
        public string UserGroup { get; set; }
        public string NewUserGroup { get; set; }
        public string NewEmail { get; set; }
        public string RequestorEmail { get; set; }
        public string ManagerEmail { get; set; }
        public string RequestType { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public Nullable<int> UpdatedByRoleId { get; set; }
        public string Response { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseMessage { get; set; }
        public string Comments { get; set; }
    }
}
