//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUserPreference
    {
        public long ID { get; set; }
        public string UserId { get; set; }
        public string EntityName { get; set; }
        public string EntityItem { get; set; }
        public string ConfigType { get; set; }
        public Nullable<int> WFConfigId { get; set; }
        public string Config { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string SessionId { get; set; }
    }
}
