//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LWorkflowGridColumn
    {
        public int Id { get; set; }
        public string LwfgcColumnName { get; set; }
        public string LwfgcUILabel { get; set; }
        public bool LwfgcShouldBeVisible { get; set; }
        public Nullable<int> LwfgcOrderByOrdinal { get; set; }
        public string LwfgcAscDesc { get; set; }
        public int LwfgcWfConfigId { get; set; }
        public int LwfgcOrdinal { get; set; }
        public string LwfgcFunctionName { get; set; }
        public string LwfgcJoinTable { get; set; }
        public string LwfgcJoinTableColumn { get; set; }
        public string LwfgcBaseTableJoinColumn { get; set; }
        public Nullable<bool> LwfgcIsEncrypted { get; set; }
    
        public virtual LWorkFlowConfig LWorkFlowConfig { get; set; }
    }
}
