//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LWorkFlowActionParameter
    {
        public int Id { get; set; }
        public string ParameterName { get; set; }
        public string ParameterValueType { get; set; }
        public string ParameterValue { get; set; }
        public int WFActionItemId { get; set; }
    
        public virtual LWorkFlowActionItem LWorkFlowActionItem { get; set; }
    }
}
