//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LWorkFlowConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LWorkFlowConfig()
        {
            this.LWorkFlowActionItems = new HashSet<LWorkFlowActionItem>();
            this.LWorkFlowActionItems1 = new HashSet<LWorkFlowActionItem>();
            this.LWorkflowGridColumns = new HashSet<LWorkflowGridColumn>();
            this.LNotifications = new HashSet<LNotification>();
        }
    
        public int Id { get; set; }
        public int LwfcWorkFlowId { get; set; }
        public string LwfcRoleId { get; set; }
        public int LwfcCompanyId { get; set; }
        public int LwfcOrdinalNumber { get; set; }
        public string LwfcDescription { get; set; }
        public bool LwfcCanCreate { get; set; }
        public bool LwfcDoNotNotify { get; set; }
        public string LwfcActingAs { get; set; }
        public bool LwfcSkip { get; set; }
        public string LwfcSkipFunctionName { get; set; }
        public string LwfcBanner { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LWorkFlowActionItem> LWorkFlowActionItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LWorkFlowActionItem> LWorkFlowActionItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LWorkflowGridColumn> LWorkflowGridColumns { get; set; }
        public virtual RWorkFlow RWorkFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNotification> LNotifications { get; set; }
    }
}
