//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RChannel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RChannel()
        {
            this.LPayees = new HashSet<LPayee>();
            this.LPortfolios = new HashSet<LPortfolio>();
            this.RSubChannels = new HashSet<RSubChannel>();
        }
    
        public int Id { get; set; }
        public int RcCompanyId { get; set; }
        public string RcName { get; set; }
        public string RcDescription { get; set; }
        public string RcPrimaryChannel { get; set; }
        public Nullable<bool> RcIsActive { get; set; }
    
        public virtual GCompany GCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LPayee> LPayees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LPortfolio> LPortfolios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSubChannel> RSubChannels { get; set; }
    }
}
