//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPayPublishEmail
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string EmailIds { get; set; }
        public string Department { get; set; }
    
        public virtual GCompany GCompany { get; set; }
    }
}
