//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RStatus
    {
        public int Id { get; set; }
        public string RsStatus { get; set; }
        public string RsDescription { get; set; }
        public int RsOwnerId { get; set; }
    
        public virtual RStatusOwner RStatusOwner { get; set; }
    }
}
