//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSupportQuickTicket
    {
        public int Id { get; set; }
        public string RsqtUILabel { get; set; }
        public string RsqtSummary { get; set; }
        public string RsqtDescription { get; set; }
        public int RsqtCategoryId { get; set; }
        public string RsqtTicketDescription { get; set; }
    
        public virtual RSupportCategory RSupportCategory { get; set; }
    }
}
