//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone_SOS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RWorkFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RWorkFlow()
        {
            this.LAudits = new HashSet<LAudit>();
            this.LWorkFlowConfigs = new HashSet<LWorkFlowConfig>();
        }
    
        public int Id { get; set; }
        public string RwfName { get; set; }
        public string RwfUILabel { get; set; }
        public string RwfBaseTableName { get; set; }
        public bool RwfCRAllowed { get; set; }
        public string RwfCRWFName { get; set; }
        public string RwfWFType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAudit> LAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LWorkFlowConfig> LWorkFlowConfigs { get; set; }
    }
}
