//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAccessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEmailConfiguration
    {
        public int Id { get; set; }
        public string GecAccountName { get; set; }
        public string GecAccountDescription { get; set; }
        public string GecEmailId { get; set; }
        public string GecDisplayName { get; set; }
        public string GecReplyTo { get; set; }
        public string GelSmtpHost { get; set; }
        public int GecPortNumber { get; set; }
        public string GecSmtpLoginId { get; set; }
        public string GecSMTPPassword { get; set; }
        public bool GecRequiresSSL { get; set; }
    }
}
