//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAccessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GKeyValue
    {
        public int Id { get; set; }
        public int GkvCompanyId { get; set; }
        public string GkvKey { get; set; }
        public string GkvValue { get; set; }
        public string GkvDescription { get; set; }
    
        public virtual GCompany GCompany { get; set; }
    }
}
